sudo: required
services:
  - docker

env:
  global:
    - secure: "3PAiitxDTadU0a1CGp+sivV16ZaEOprcs0eWIk23+qZ+2Q6+M82loh/xm7bxGW/4SNLgdvFgQ9Rak4XTYy4me1GGvNK14EB9zIoSdqumr3kUqL8nuU4seMKDF+DUMGBxd3o7Z/AGk3Nv3X+en9nzqs2a9w07HjBqjyWjMnZJtEc56CoEqKSR2/qyUs50C0JkLn6oB9/7AaUEj6JPDW/G+amt/caGaq0CDKytAoAQ+/194RlKfoHuHgldAQptgXwo1agUmLZ3qeEiV/lQxwVbVGyVDzFOjSMFfNEUeLU95W4b9oQuFqI54J6K/2E1tP/Dqg+jL3MW68CYHYuQaUnoML/FAIvoh6e9MHX52GvJ15q038G47K3gAWjIcleuNC6RhJHJQIJrKs5Tv2ihj28oX4PXMDdzTxB/mTqsnxhgKeY4emavTTnhQWRLNyarjBHaZOcNuj9Jvzp80N+jNrqYP+k3/ixunjkWUX1uGkjcntubHaSh2Rln/Jlx6nHweSu09C5EXHJz9K/FbgmbHM7Rypw+UnuIbIrjLg7ylVravwRG8zLn4RKQbGtmoJt1xnWITDbaOitT8TayB/Tf4fhL7Exo8MrFrRULT/IlcD5VfEUGLdOVrnhEhw59yp990w7z8E1lMI6QQs72vu9nbrBaHxyrHV4ak9HXT2wjmbSHthE="
    - secure: "JyUnSi8HHGyV6HSu7gjfMq9HEt3PXsU+p+NtFS8xITDZm67EnQplRAS1O2U5Gx64PBQ4kdYVzL5taTB3//qqXP+mwF0TKabCuklDWo0E9HfAgSFQeDd+b0q1ycSFerIn1zlAG/4UCLJJzdARVyb3gMHBh82eVVuKBWnUQzoXgSHXw/BO6KtZmwiOeBTtsTv13nMPcK10g+yHocciDGUeMCRY/pOoKji2OVGfjk2ywsapWhgdZEC6+0z885I5s/VsscBT7WliYTsYY64sxzi4XaDmN+xFkDy0LOYAFTxBaH1TMI+T5iSnj5rOnbzEvw66sA1184ODEZY80D40xSvpQCGOwXPtHrDDqr8rixMY9Bnbe0MYbmBOx91rKNV8o6pw6jYkeEDQ0e+mxstmiS1YZ0yYN7Bc5tRft5Jip+Gg/OBRU6s9AFqIF6WdAGJ94lKWbi8sqL8Qb0blo1LdQ9OlpMTfjApYWQfenh2BKvcuCr6MuQ4pW0+AHZRrv/OTwKjQCRe8DHlTjsM3sUgnVfGVtt6XMEKLATwf3PmO5xOykw+gpsbaGUIdb91Rcifu7WcyqASXJqT/I8Y0mQWbhdAJqthbwuNousZln1EdIC3YGLSHWeo+iY3YssJnmSOyVMDcVodJePSSlctIUZqOSOwa+gXLSzSsiPiap7p34W6yw+g="

script:
  - make image
  - IMGTAG=travis-${TRAVIS_BUILD_ID} make tag-image
  - IMGTAG=latest make tag-image
  - make docker-login 
  - make push-image
