apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.port: "8484"
spec:
  ports:
  - port: 8484
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}